module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.bulkInsert(
      'meetups',
      [
        {
          title: 'Meetup_1',
          description: 'Descrição Meetup_1',
          location: 'Localização Meetup_1',
          user_id: 1,
          banner_id: 5,
          schedule: '2019-11-02 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_2',
          description: 'Descrição Meetup_2',
          location: 'Localização Meetup_2',
          user_id: 1,
          banner_id: 6,
          schedule: '2019-11-03 04:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_3',
          description: 'Descrição Meetup_3',
          location: 'Localização Meetup_3',
          user_id: 1,
          banner_id: 7,
          schedule: '2019-11-03 05:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_4',
          description: 'Descrição Meetup_4',
          location: 'Localização Meetup_4',
          user_id: 1,
          banner_id: 8,
          schedule: '2019-11-02 06:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_5',
          description: 'Descrição Meetup_5',
          location: 'Localização Meetup_5',
          user_id: 1,
          banner_id: 5,
          schedule: '2019-11-02 07:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_6',
          description: 'Descrição Meetup_6',
          location: 'Localização Meetup_6',
          user_id: 1,
          banner_id: 6,
          schedule: '2019-11-03 07:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_7',
          description: 'Descrição Meetup_7',
          location: 'Localização Meetup_7',
          user_id: 1,
          banner_id: 7,
          schedule: '2019-11-04 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_8',
          description: 'Descrição Meetup_8',
          location: 'Localização Meetup_8',
          user_id: 1,
          banner_id: 8,
          schedule: '2019-11-05 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_9',
          description: 'Descrição Meetup_9',
          location: 'Localização Meetup_9',
          user_id: 2,
          banner_id: 5,
          schedule: '2019-11-06 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_10',
          description: 'Descrição Meetup_10',
          location: 'Localização Meetup_10',
          user_id: 2,
          banner_id: 6,
          schedule: '2019-11-05 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_11',
          description: 'Descrição Meetup_11',
          location: 'Localização Meetup_11',
          user_id: 2,
          banner_id: 7,
          schedule: '2019-11-04 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_12',
          description: 'Descrição Meetup_12',
          location: 'Localização Meetup_12',
          user_id: 2,
          banner_id: 8,
          schedule: '2019-11-05 06:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_13',
          description: 'Descrição Meetup_13',
          location: 'Localização Meetup_13',
          user_id: 2,
          banner_id: 5,
          schedule: '2019-11-05 04:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_14',
          description: 'Descrição Meetup_14',
          location: 'Localização Meetup_14',
          user_id: 2,
          banner_id: 6,
          schedule: '2019-11-06 04:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_15',
          description: 'Descrição Meetup_15',
          location: 'Localização Meetup_15',
          user_id: 2,
          banner_id: 7,
          schedule: '2019-11-07 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_16',
          description: 'Descrição Meetup_16',
          location: 'Localização Meetup_16',
          user_id: 2,
          banner_id: 8,
          schedule: '2019-11-07 04:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_17',
          description: 'Descrição Meetup_17',
          location: 'Localização Meetup_17',
          user_id: 1,
          banner_id: 9,
          schedule: '2019-11-01 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_18',
          description: 'Descrição Meetup_18',
          location: 'Localização Meetup_18',
          user_id: 1,
          banner_id: 10,
          schedule: '2019-11-01 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 1,
          banner_id: 11,
          schedule: '2019-11-01 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 12,
          schedule: '2019-11-01 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 1,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_19',
          description: 'Descrição Meetup_19',
          location: 'Localização Meetup_19',
          user_id: 2,
          banner_id: 11,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 12,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 13,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 14,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 15,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          title: 'Meetup_20',
          description: 'Descrição Meetup_20',
          location: 'Localização Meetup_20',
          user_id: 2,
          banner_id: 16,
          schedule: '2019-11-10 03:00:00+00',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    ),

  down: queryInterface => queryInterface.bulkDelete('meetups', null, {}),
};
